services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: Bank_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net
    restart: always

  app:
    build: .
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Bank_DB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: docker-secret-key
      JWT_EXPIRATION: 3600000
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - spring-net
    restart: always

volumes:
  postgres_data:

networks:
  spring-net:
